### ISSUE TITLE
Read date from xlsx

### ISSUE THREAD

**Issue by DMGPage** [box/spout#283]
I have this file: [nm_sd_apturesana_21072016.xlsx](https://github.com/box/spout/files/385702/nm_sd_apturesana_21072016.xlsx)
I can not understand why spout returns:
```
array (48) [
    string (2) "1."
    string (11) "40003691882"
    string UTF-8 (45) "Sabiedrība ar ierobežotu atbildību "PRINTECH""
    integer 42570
    integer 42572
    ...
]
```
Row contains two dates "2016.07.19" and "21.07.2016". Both cells are with date format so why it returns integers "42570" and "42572". And how I can get correct date from them?

**Comment by adrilo** [comment]
Hi @DMGPage,

After investigation, this issue is caused by prefixes in the XML file defining the styles (and therefore the date format). Spout expects XML tags like `<cellXfs>` but the software you're using to generate the XML file uses `<x:cellXfs>` for all tags.
There was a similar issue (#233) that was fixed for other XML files but the `styles.xml` file was left untouched. The same changes also need to be applied to this file.

**Comment by mjanis** [comment]
Still didn't work with date like '5/26/2015'. Cols J ,K, L in attached file.

[tests.xlsx](https://github.com/box/spout/files/466831/tests.xlsx)

**Comment by adrilo** [comment]
This issue is caused by something different. I'm opening a new issue to track this one.

**Comment by stefangabos** [comment]
Hello, any news on this one? This is still not working for dates like 6/3/2016. Thanks!
